#!/bin/bash

DRIVERS="*.jar"
TESTS="*.lambda"

for driver in $DRIVERS
do
    for prog in $TESTS
    do
        echo "Testing $prog with $driver"
        java -Xss8M -jar $driver $prog
        status=$?
        echo "exit code $status"
        if [[ $status != 0 ]]
        then
            exit $status
        fi
        echo ""
    done
done
